"""
ref https://www.stereolabs.com/docs/api/python/classpyzed_1_1sl_1_1OBJECT__SUBCLASS.html

OBJECT_SUBCLASS	OBJECT_CLASS
PERSON	PERSON
PERSON_HEAD	PERSON
BICYCLE	VEHICLE
CAR	VEHICLE
MOTORBIKE	VEHICLE
BUS	VEHICLE
TRUCK	VEHICLE
BOAT	VEHICLES
BACKPACK	BAG
HANDBAG	BAG
SUITCASE	BAG
BIRD	ANIMAL
CAT	ANIMAL
DOG	ANIMAL
HORSE	ANIMAL
SHEEP	ANIMAL
COW	ANIMAL
CELLPHONE	ELECTRONICS
LAPTOP	ELECTRONICS
BANANA	FRUIT_VEGETABLE
APPLE	FRUIT_VEGETABLE
ORANGE	FRUIT_VEGETABLE
CARROT	FRUIT_VEGETABLE
SPORTSBALL	SPORT
"""

import pyzed.sl as sl

subclass2str = {
    sl.OBJECT_SUBCLASS.PERSON: "PERSON",
    sl.OBJECT_SUBCLASS.PERSON_HEAD: "PERSON_HEAD",
    sl.OBJECT_SUBCLASS.BICYCLE: "BICYCLE",
    sl.OBJECT_SUBCLASS.CAR: "CAR",
    sl.OBJECT_SUBCLASS.MOTORBIKE: "MOTORBIKE",
    sl.OBJECT_SUBCLASS.BUS: "BUS",
    sl.OBJECT_SUBCLASS.TRUCK: "TRUCK",
    sl.OBJECT_SUBCLASS.BOAT: "BOAT",
    sl.OBJECT_SUBCLASS.BACKPACK: "BACKPACK",
    sl.OBJECT_SUBCLASS.HANDBAG: "HANDBAG",
    sl.OBJECT_SUBCLASS.SUITCASE: "SUITCASE",
    sl.OBJECT_SUBCLASS.BIRD: "BIRD",
    sl.OBJECT_SUBCLASS.CAT: "CAT",
    sl.OBJECT_SUBCLASS.DOG: "DOG",
    sl.OBJECT_SUBCLASS.HORSE: "HORSE",
    sl.OBJECT_SUBCLASS.SHEEP: "SHEEP",
    sl.OBJECT_SUBCLASS.COW: "COW",
    sl.OBJECT_SUBCLASS.CELLPHONE: "CELLPHONE",
    sl.OBJECT_SUBCLASS.LAPTOP: "LAPTOP",
    sl.OBJECT_SUBCLASS.BANANA: "BANANA",
    sl.OBJECT_SUBCLASS.APPLE: "APPLE",
    sl.OBJECT_SUBCLASS.ORANGE: "ORANGE",
    sl.OBJECT_SUBCLASS.CARROT: "CARROT",
    sl.OBJECT_SUBCLASS.SPORTSBALL: "SPORTSBALL",
}
